# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :build_and_export do
    increment_version_number(
      version_number: "1.1"
    )
    increment_build_number

    gym

    firebase_app_distribution(service_credentials_file: "/Users/lam/naukma/Apple/catsanddogs-b9f74-40f4c4de5c90.json", 
    ipa_path: "/Users/lam/naukma/Apple/CatsAndDogs/output/CatsAndDogs.ipa",
    release_notes: "Release notes", 
    testers: "o.frankiv@ukma.edu.ua")
    

    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Take screenshots"
  lane :take_screenshots do
    capture_screenshots
  end

end

